export const categoryData = [
  {
    id: 1,
    title: "The Evolution of Sustainable Architecture in 2025",
    category: "Architecture",
    excerpt:
      "Discover how architects are revolutionizing sustainable design with breakthrough materials and innovative approaches to create carbon-negative buildings.",
    author: "Emma Richardson",
    date: "January 28, 2025",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "23.5k",
    shares: "1.2k",
    readTime: "8 min read",
  },
  {
    id: 2,
    title: "The Future of AI in Healthcare",
    category: "Health",
    excerpt:
      "Explore how artificial intelligence is transforming patient care and diagnostics in the healthcare industry.",
    author: "John Doe",
    date: "February 15, 2025",
    image: "https://images.unsplash.com/photo-1581091870620-1c1c1c1c1c1c",
    likes: "15.3k",
    shares: "900",
    readTime: "6 min read",
  },
  {
    id: 3,
    title: "The Rise of Electric Vehicles",
    category: "Technology",
    excerpt:
      "A deep dive into the advancements in electric vehicle technology and its impact on the automotive industry.",
    author: "Sarah Johnson",
    date: "March 10, 2025",
    image: "https://images.unsplash.com/photo-1601582022020-1c1c1c1c1c1c",
    likes: "30.1k",
    shares: "2.5k",
    readTime: "7 min read",
  },
  {
    id: 4,
    title: "Understanding Climate Change: A Global Perspective",
    category: "Environment",
    excerpt:
      "An overview of climate change, its causes, and the global efforts to combat its effects.",
    author: "Michael Smith",
    date: "April 5, 2025",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "18.7k",
    shares: "1.1k",
    readTime: "9 min read",
  },
  {
    id: 5,
    title: "The Impact of Social Media on Politics",
    category: "Politics",
    excerpt:
      "Analyzing how social media platforms are shaping political discourse and public opinion.",
    author: "Jessica Lee",
    date: "May 20, 2025",
    image: "https://images.unsplash.com/photo-1517436072-9c4b4b4b4b4b",
    likes: "22.4k",
    shares: "1.5k",
    readTime: "5 min read",
  },
  {
    id: 6,
    title: "The Future of Remote Work",
    category: "Business",
    excerpt:
      "Examining the long-term effects of remote work on productivity and company culture.",
    author: "David Brown",
    date: "June 12, 2025",
    image: "https://images.unsplash.com/photo-1581091870620-1c1c1c1c1c1c",
    likes: "12.8k",
    shares: "600",
    readTime: "4 min read",
  },
  {
    id: 7,
    title: "Exploring the Universe: The Latest in Space Exploration",
    category: "Science",
    excerpt:
      "A look at the latest missions and discoveries in space exploration and what they mean for humanity.",
    author: "Alice Green",
    date: "July 18, 2025",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "25.0k",
    shares: "1.8k",
    readTime: "10 min read",
  },
  {
    id: 8,
    title: "The Art of Mindfulness: Techniques for Everyday Life",
    category: "Lifestyle",
    excerpt:
      "Discover practical mindfulness techniques to reduce stress and improve mental well-being.",
    author: "Emma Wilson",
    date: "August 22, 2025",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "19.3k",
    shares: "1.0k",
    readTime: "6 min read",
  },
  {
    id: 9,
    title: "The Evolution of Fashion: Trends Through the Decades",
    category: "Fashion",
    excerpt:
      "A retrospective look at how fashion trends have evolved over the years and what influences them.",
    author: "Sophia Taylor",
    date: "September 30, 2025",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "14.5k",
    shares: "800",
    readTime: "7 min read",
  },
  {
    id: 10,
    title: "The Importance of Mental Health Awareness",
    category: "Health",
    excerpt:
      "Understanding the significance of mental health awareness and its impact on society.",
    author: "James Anderson",
    date: "October 14, 2025",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "20.2k",
    shares: "1.3k",
    readTime: "5 min read",
  },
  {
    id: 11,
    title: "The Future of Renewable Energy",
    category: "Environment",
    excerpt:
      "Exploring the advancements in renewable energy technologies and their potential impact.",
    author: "Olivia Martinez",
    date: "November 8, 2025",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "28.4k",
    shares: "2.0k",
    readTime: "8 min read",
  },
  {
    id: 12,
    title: "The Role of Technology in Education",
    category: "Education",
    excerpt:
      "How technology is transforming the educational landscape and enhancing learning experiences.",
    author: "Liam Harris",
    date: "December 1, 2025",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "16.7k",
    shares: "1.1k",
    readTime: "6 min read",
  },
  {
    id: 13,
    title: "The Impact of Climate Change on Wildlife",
    category: "Environment",
    excerpt:
      "Investigating how climate change is affecting wildlife and biodiversity around the globe.",
    author: "Mia Clark",
    date: "January 15, 2026",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "21.9k",
    shares: "1.4k",
    readTime: "7 min read",
  },
  {
    id: 14,
    title: "The Future of Cryptocurrency",
    category: "Finance",
    excerpt:
      "Analyzing the trends and future prospects of cryptocurrency in the global economy.",
    author: "Noah Lewis",
    date: "February 20, 2026",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "35.2k",
    shares: "3.0k",
    readTime: "9 min read",
  },
  {
    id: 15,
    title: "The Influence of Music on Culture",
    category: "Culture",
    excerpt:
      "Exploring how music shapes cultural identity and influences societal change.",
    author: "Ava Walker",
    date: "March 25, 2026",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "18.1k",
    shares: "1.0k",
    readTime: "5 min read",
  },
  {
    id: 16,
    title: "The Benefits of a Plant-Based Diet",
    category: "Health",
    excerpt:
      "Understanding the health benefits of adopting a plant-based diet and its impact on well-being.",
    author: "Isabella Hall",
    date: "April 30, 2026",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "27.3k",
    shares: "2.2k",
    readTime: "6 min read",
  },
  {
    id: 17,
    title: "The Future of Urban Development",
    category: "Urban Planning",
    excerpt:
      "Examining innovative urban development strategies for sustainable cities.",
    author: "Ethan Young",
    date: "May 15, 2026",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "24.0k",
    shares: "1.8k",
    readTime: "8 min read",
  },
  {
    id: 18,
    title: "The Impact of Globalization on Local Cultures",
    category: "Culture",
    excerpt:
      "Analyzing how globalization affects local cultures and traditions around the world.",
    author: "Charlotte King",
    date: "June 10, 2026",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "15.6k",
    shares: "900",
    readTime: "7 min read",
  },
  {
    id: 19,
    title: "The Role of Artificial Intelligence in Business",
    category: "Business",
    excerpt:
      "Exploring how AI is transforming business operations and decision-making processes.",
    author: "Amelia Wright",
    date: "July 22, 2026",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "29.8k",
    shares: "2.5k",
    readTime: "9 min read",
  },
  {
    id: 20,
    title: "The Future of Work: Trends and Predictions",
    category: "Business",
    excerpt:
      "A look at the evolving landscape of work and the trends shaping the future.",
    author: "Lucas Scott",
    date: "August 18, 2026",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    likes: "32.1k",
    shares: "3.1k",
    readTime: "10 min read",
  },
];
